site:
  title: MeglSiki Note
  start_page: main-note::index.adoc
content:
  sources:
    - url: https://github.com/MeglSiki/note-main
      branches: HEAD
      start_path: documents

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
