name: Copy Build Output to Another Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      OTHER_REPO: meglsiki/meglsiki-portal
      GIT_USER_EMAIL: megl000.dev@gmail.com
      GIT_USER_NAME: MeglSiki

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build
        run: npm run build

      - name: Clone other repo
        run: |
          git clone https://github.com/${OTHER_REPO}.git /tmp/other-repo
          cd /tmp/other-repo
          git config user.email "${GIT_USER_EMAIL}"
          git config user.name "${GIT_USER_NAME}"
          git checkout main

      - name: Copy build output to other repo
        run: cp -r build/site /tmp/other-repo/public/notes

      - name: Commit and push changes
        run: |
          cd /tmp/other-repo
          git add .
          git commit -m "Auto commit by meglsiki-note"
          git push https://github.com/${OTHER_REPO}.git HEAD:main
