name: Copy Build Output to Another Repository

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build
        run: |
          npm i
          npm run build

      - name: Clone other repo
        run: |
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/MeglSiki/meglsiki-portal
          git config user.email "megl000.dev@gmail.com"
          git config user.name "MeglSiki"
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/MeglSiki/meglsiki-portal.git /tmp/other-repo
          cd /tmp/other-repo
          git checkout main

      - name: Copy build output to other repo
        run: cp -r build/site /tmp/other-repo/public/notes

      - name: Commit and push changes
        run: |
          cd /tmp/other-repo
          git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/MeglSiki/meglsiki-portal
          git config user.email "megl000.dev@gmail.com"
          git config user.name "MeglSiki"
          git add .
          git commit -m "Auto commit by meglsiki-note"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/MeglSiki/meglsiki-portal.git HEAD:main
